version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'KodotiWallet'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./src/core/database/mysql:/var/lib/mysql
      - ./src/core/database/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql

networks:
  servers:
    name: api
