version: '3.7'

services:
  backend:
    build: .
    container_name: api.wallet
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    networks:
      - 'servers'
    environment:
      DOCKER: 'true'
      NODE_ENV: ${NODE_ENV:-dev}
      PORT: ${PORT:-3000}

networks:
  servers:
    name: api
